[package]
name = "rotth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.1.5"
chumsky = "0.8.0"
somok = "1.3.0"
clap = { version = "3", features = ["derive"] }
simplearena = { path = "simplearena" }
indoc = "1.0.4"
thiserror = "1.0.30"
