[package]
name = "rotth-lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos.workspace = true
smol_str.workspace = true
internment.workspace = true
spanner = { path = "../spanner" }
