[package]
name = "rotth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.1.5"
somok = "1.5.0"
clap = { version = "3", features = ["derive"] }
simplearena = { path = "../simplearena" }
indoc = "1.0.4"
fnv = "1.0"
rotth-lexer = { path = "../rotth-lexer" }
rotth-parser = { path = "../rotth-parser" }
spanner = { path = "../spanner" }
chumsky = { git = "https://github.com/zesterer/chumsky.git" }
thiserror = "1.0"
smol_str = "0.1"
